# Generated by Django 4.1 on 2022-09-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
